Try adding a second continuation argument to `Future.apply`, which takes an error handler.